language: generic
dist: trusty
sudo: true
cache:
    directories:
      - vendor/
before_script:
  - ls -la ./
  - touch storage/logs/lumen.log
  - sudo chmod 777 -Rf storage/
  - echo $PWD
  - sudo mkdir /www
  - sudo ln -s $PWD /www/gandalf.api
  - cp ./.env.example ./.env
  - bash puppet/initial/travis/init.sh
  - echo 127.0.0.1 gandalf.dev | sudo tee -a /etc/hosts
  - php7.0 -i
  - composer install --prefer-source
script:
  - vendor/bin/codecept run
  - vendor/bin/phpcs ./app --standard=PSR2 --warning-severity=0
after_failure:
  - ls -l /etc/nginx
  - ls -l /etc/nginx/sites-enabled
  - echo $PWD
  - ls -la ./
  - ls -la ../
  - ls -l /www
  - cat /etc/nginx/sites-enabled/*
  - cat /etc/nginx/nginx.conf
  - cat /var/log/www/*.log;
  - cat /var/log/php-fpm.log;
  - cat /var/log/nginx.log;
  - cat $PWD/storage/logs/lumen.log;
